apiVersion: v1
kind: Service
metadata:
  name: spring-boot-docker
spec:
  ports:
  - port: 8099
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: spring-boot-docker
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  type: LoadBalancer

