apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker-deployment
  labels:
    app: spring-boot-docker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spring-boot-docker
  template:
    metadata:
      labels:
        app: spring-boot-docker
    spec:
      containers:
      - name: spring-boot-docker
        image: swyoo/spring-boot-docker
        ports:
        - containerPort: 8080
